# .github/workflows/ci-cd.yml

name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ”½ Repozitoriyani clone qilish
      uses: actions/checkout@v4

    - name: ğŸŸ¢ Node.js versiyasini o'rnatish
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ğŸ“¦ Paketlarni oâ€˜rnatish
      run: npm install

    # (Agar sizda `npm run build` kerak boâ€˜lsa, shu yerga qoâ€˜shing)
    # - name: ğŸ— Build
    #   run: npm run build

    - name: ğŸ“¤ Serverga deploy qilish (SCP orqali)
      if: github.ref == 'refs/heads/main'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "."
        target: "/home/root/mini-app"

    - name: ğŸ” Serverda PM2 restart
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/YOUR_USER/your-project-folder
          npm install
          pm2 delete your-app-name || true
          pm2 start backend/index.js --name your-app-name
          pm2 save
